Repository opticdev/optic, pull requests merged in 2020-07, with the labels that each got.

#229 Surfaced proxy port to user
  workspaces/cli-shared/src/command-and-proxy-session-manager.ts
Labels: enhancement

#234 init: updated optic.yml template
  workspaces/local-cli/src/commands/init.ts
Labels: enhancement

#246 Enable NPM Deployment on Release
  .github/workflows/release.yml
Labels: enhancement

#239 query parameters should save in capture
  workspaces/cli-config/src/index.ts
  workspaces/cli-shared/package.json
  workspaces/cli-shared/src/command-and-proxy-session-manager.ts
  workspaces/cli-shared/src/httptoolkit-capturing-proxy.ts
  workspaces/cli-shared/src/query/build-query-string-parser.ts
  workspaces/cli-shared/src/query/parsers/query-string/DefaultQueryParser.ts
  workspaces/cli-shared/src/query/parsers/values/DefaultValueParser.ts
  workspaces/cli-shared/src/query/query-parser-interfaces.ts
  workspaces/local-cli/src/shared/verify.ts
  yarn.lock
Labels: enhancement

#245 Diff Flow Bug Fixes
  core/optic/shared/src/main/scala/com/useoptic/ux/DiffResultHelper.scala
  workspaces/agent-cli/package.json
  workspaces/ci-cli/package.json
  workspaces/cli-client/package.json
  workspaces/cli-config/package.json
  workspaces/cli-scripts/package.json
  workspaces/cli-server/package.json
  workspaces/cli-shared/package.json
  workspaces/client-utilities/package.json
  workspaces/domain-types/package.json
  workspaces/domain-utilities/package.json
  workspaces/domain/package.json
  workspaces/local-cli/package.json
  workspaces/saas-types/package.json
  workspaces/snapshot-tests/package.json
  workspaces/ui/package.json
  workspaces/ui/src/components/diff/v2/CaptureManagerPage.js
Labels: enhancement

#254 Fixes NPM Release Flow
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: fix

#258 Configuring Homebrew Release Flow
  .github/workflows/release.yml
Labels: enhancement

#259 Configuring Debian Release Flow #258
  .github/deployDebian/Dockerfile
  .github/deployDebian/action.yml
  .github/deployDebian/entrypoint.sh
  .github/workflows/release.yml
  .github/workflows/testDebian.yml
  workspaces/local-cli/package.json
Labels: enhancement

#267 Fixed issue where GitHub Actions Checked Out Non Existent Branch
  .github/deployDebian/entrypoint.sh
  .github/workflows/release.yml
Labels: bug

#293 Fixed bug where events wouldn't render initially
  workspaces/ui/src/components/loaders/ApiLoader.js
Labels: fix
