Repository opticdev/optic, pull requests merged in 2020-10, with the labels that each got.

#376 Release Coverage Flag
  workspaces/agent-cli/package.json
  workspaces/analytics/package.json
  workspaces/ci-cli/package.json
  workspaces/cli-client/package.json
  workspaces/cli-config/package.json
  workspaces/cli-scripts/package.json
  workspaces/cli-server/package.json
  workspaces/cli-shared/package.json
  workspaces/cli-shared/src/captures/avro/file-system/capture-saver-with-diffs.ts
  workspaces/client-utilities/package.json
  workspaces/diff-engine/package.json
  workspaces/local-cli/package.json
  workspaces/local-cli/src/commands/run.ts
  workspaces/local-cli/src/commands/start.ts
  workspaces/local-cli/src/shared/coverage.ts
  workspaces/local-cli/src/shared/local-cli-task-runner.ts
  workspaces/saas-types/package.json
  workspaces/snapshot-tests/package.json
  workspaces/ui/package.json
  yarn.lock
Labels: minor

#381 Optic for your code tests
  workspaces/agent-cli/package.json
  workspaces/analytics/package.json
  workspaces/analytics/src/interfaces/Events.ts
  workspaces/ci-cli/package.json
  workspaces/cli-client/package.json
  workspaces/cli-config/package.json
  workspaces/cli-config/src/index.ts
  workspaces/cli-scripts/package.json
  workspaces/cli-server/package.json
  workspaces/cli-shared/package.json
  workspaces/cli-shared/src/captures/avro/file-system/capture-saver.ts
  workspaces/cli-shared/src/command-and-proxy-session-manager.ts
  workspaces/cli-shared/src/index.ts
  workspaces/cli-shared/src/tasks/await-up.ts
  workspaces/cli-shared/src/tasks/index.ts
  workspaces/client-utilities/package.json
  workspaces/diff-engine/package.json
  workspaces/local-cli/.optic-daemon.log
  workspaces/local-cli/package.json
  workspaces/local-cli/src/commands/scripts.ts
  workspaces/local-cli/src/shared/local-cli-task-runner.ts
  workspaces/local-cli/src/shared/spawn-process.ts
  workspaces/local-cli/src/shared/verify/verify.ts
  workspaces/saas-types/package.json
  workspaces/snapshot-tests/package.json
  workspaces/ui/package.json
  workspaces/ui/src/Analytics.js
  yarn.lock
Labels: patch

#394 Derive undocumented urls of diffs produced through new Rust diff engine
  workspaces/cli-server/src/diffs/on-demand.ts
  workspaces/diff-engine/src/interactions/result.rs
  workspaces/diff-engine/src/interactions/visitors/diff.rs
  workspaces/diff-engine/tests/interaction_diff.rs
  workspaces/diff-engine/tests/snapshots/interaction_diff__can_yield_interactive_diff_result-2.snap
  workspaces/diff-engine/tests/snapshots/interaction_diff__can_yield_interactive_diff_result.snap
  workspaces/diff-engine/tests/snapshots/interaction_diff__can_yield_interactive_diff_result__results.snap
  workspaces/diff-engine/tests/snapshots/interaction_diff__can_yield_unmatched_request_url__fingerprints.snap
  workspaces/diff-engine/tests/snapshots/interaction_diff__can_yield_unmatched_request_url__results.snap
Labels: behind-feature-flag

#403 Fix bug where Rust diff engine's locally-compiled binary could not be found
  workspaces/diff-engine/ts/config.ts
  workspaces/diff-engine/ts/index.ts
Labels: behind-feature-flag
