Repository opticdev/optic, pull requests merged in 2020-09, with the labels that each got.

#329 Fix a bug where InteractionBodyViewer would crash the app rendering new endpoints with empty bodies
  workspaces/ui/src/components/diff/v2/DiffNewRegions.js
  workspaces/ui/src/components/diff/v2/shape_viewers/InteractionBodyViewer.js
Labels: behind-feature-flag, bug

#325 [GitBot] Add Publish and Compare Commands
  .github/workflows/deploySpec.yml
  package.json
  workspaces/ci-cli/README.md
  workspaces/ci-cli/package.json
  workspaces/cli-shared/package.json
  workspaces/ui/.env.development
  workspaces/ui/config/paths.js
  workspaces/ui/package.json
  workspaces/ui/public/specs/hackathon.json
  workspaces/ui/public/specs/test.json
  workspaces/ui/scripts/build-spec.js
  workspaces/ui/scripts/start-local-spec.js
  workspaces/ui/src/components/navigation/Navbar.js
  workspaces/ui/src/components/support/SpecHomePage.js
  workspaces/ui/src/contexts/MockDataContext.js
  workspaces/ui/src/contexts/SpecViewerContext.js
  workspaces/ui/src/entrypoints/index.js
  workspaces/ui/src/entrypoints/spec-viewer.js
  workspaces/ui/src/entrypoints/specEntrypoints.js
  workspaces/ui/src/specIndex.js
  yarn.lock
Labels: feature

#331 Added analytics package to cli-client
  workspaces/cli-client/package.json
  yarn.lock
Labels: fix

#344 Fix bug where text bodies of interactions would render an empty InteractionBodyViewer
  workspaces/ui/public/example-sessions/diff-test-cases.json
  workspaces/ui/src/components/diff/v2/shape_viewers/InteractionBodyViewer.js
Labels: behind-feature-flag, bug

#345 Fix bug where added fields describing object or array were not highlighted in DiffViewer
  workspaces/ui/src/components/diff/v2/shape_viewers/InteractionBodyViewer.js
Labels: behind-feature-flag, bug

#355 Fix small bugs in on-boarding flow
  .github/deployDebian/entrypoint.sh
  .github/workflows/bump.yml
  .github/workflows/release.yml
  Readme.md
  workspaces/agent-cli/package.json
  workspaces/analytics/package.json
  workspaces/analytics/src/events/onboarding.ts
  workspaces/analytics/src/events/wildcard.ts
  workspaces/analytics/src/interfaces/Events.ts
  workspaces/ci-cli/package.json
  workspaces/cli-client/package.json
  workspaces/cli-config/package.json
  workspaces/cli-scripts/package.json
  workspaces/cli-server/package.json
  workspaces/cli-shared/package.json
  workspaces/client-utilities/package.json
  workspaces/local-cli/package.json
  workspaces/local-cli/src/commands/init.ts
  workspaces/local-cli/src/commands/login.ts
  workspaces/saas-types/package.json
  workspaces/scripts/bump.js
  workspaces/snapshot-tests/package.json
  workspaces/ui/no
  workspaces/ui/package.json
  yarn.lock
Labels: patch

#357 edited secret name
  .github/workflows/bump.yml
Labels: fix

#358 fixed bug where debian wasnt releasing
  .github/deployDebian/action.yml
  .github/workflows/release.yml
Labels: fix

#361 init on-boarding improvements. fix debian optic
  .github/deployDebian/action.yml
  .github/workflows/bump.yml
  .github/workflows/release.yml
  Readme.md
  workspaces/agent-cli/package.json
  workspaces/analytics/package.json
  workspaces/ci-cli/package.json
  workspaces/cli-client/package.json
  workspaces/cli-config/package.json
  workspaces/cli-scripts/package.json
  workspaces/cli-server/package.json
  workspaces/cli-shared/package.json
  workspaces/client-utilities/package.json
  workspaces/local-cli/package.json
  workspaces/local-cli/src/commands/init.ts
  workspaces/saas-types/package.json
  workspaces/snapshot-tests/package.json
  workspaces/ui/package.json
  workspaces/ui/src/Analytics.js
Labels: patch

#363 adjusted all jobs to require npm
  .github/workflows/release.yml
Labels: fix
