Repository opticdev/optic, pull requests merged in 2021-02, with the labels that each got.

#555 Upgrade diff-engine to Tokio v1
  Cargo.lock
  workspaces/diff-engine/Cargo.toml
  workspaces/diff-engine/cli/Cargo.toml
  workspaces/diff-engine/cli/src/main.rs
  workspaces/diff-engine/src/streams/http_interaction.rs
  workspaces/diff-engine/tests/http_interactions.rs
  workspaces/diff-engine/tests/interaction_diff.rs
Labels: chore

#556 fix: sanitize git branch name for use in docker image tags
  .github/workflows/deployDemo.yml
  Taskfile.yml
  bin/clean-docker-tag
  workspaces/ui/Taskfile.yml
Labels: fix

#574 Implement Spec Loader that can produce single event stream from spec changes distributed in multiple files
  .env.beta
  .env.latest
  workspaces/cli-config/src/index.ts
  workspaces/cli-server/package.json
  workspaces/cli-server/src/diffs/index.ts
  workspaces/cli-server/src/diffs/on-demand.ts
  workspaces/cli-server/src/routers/spec-router.ts
  workspaces/cli-server/src/sessions.ts
  workspaces/diff-engine/cli/src/main.rs
  workspaces/diff-engine/lib/index.d.ts
  workspaces/diff-engine/lib/index.js
  workspaces/diff-engine/src/events/endpoint.rs
  workspaces/diff-engine/src/events/mod.rs
  workspaces/diff-engine/src/events/rfc.rs
  workspaces/diff-engine/src/events/shape.rs
  workspaces/diff-engine/src/events/snapshots/optic_diff_engine__events__spec_chunk__test__constructs_valid_batch_chunks__empty_events.snap
  workspaces/diff-engine/src/events/snapshots/optic_diff_engine__events__spec_chunk__test__constructs_valid_batch_chunks__missing_batch_start.snap
  workspaces/diff-engine/src/events/snapshots/optic_diff_engine__events__spec_chunk__test__constructs_valid_batch_chunks__missing_end_event.snap
  workspaces/diff-engine/src/events/snapshots/optic_diff_engine__events__spec_chunk__test__constructs_valid_batch_chunks__missing_parent_id.snap
  workspaces/diff-engine/src/events/snapshots/optic_diff_engine__events__spec_chunk__test__constructs_valid_batch_chunks__nested_batch_event.snap
  workspaces/diff-engine/src/events/snapshots/optic_diff_engine__events__spec_chunk__test__constructs_valid_batch_chunks__out_of_order_end_event.snap
  workspaces/diff-engine/src/events/spec_chunk.rs
  workspaces/diff-engine/src/lib.rs
  workspaces/diff-engine/src/projections/mod.rs
  workspaces/diff-engine/src/projections/spec_events.rs
  workspaces/diff-engine/src/state/endpoint.rs
  workspaces/diff-engine/src/state/shape.rs
  workspaces/diff-engine/src/streams/diff.rs
  workspaces/diff-engine/src/streams/mod.rs
  workspaces/diff-engine/src/streams/spec_chunks.rs
  workspaces/diff-engine/src/streams/spec_events.rs
  workspaces/diff-engine/tests/fixtures/split-spec-changes/0001.json
  workspaces/diff-engine/tests/fixtures/split-spec-changes/0002.json
  workspaces/diff-engine/tests/fixtures/split-spec-changes/debug-folder/.gitignore
  workspaces/diff-engine/tests/fixtures/split-spec-changes/other-type.json
  workspaces/diff-engine/tests/fixtures/split-spec-changes/specification.json
  workspaces/diff-engine/tests/snapshots/events__spec_should_deserialize.snap
  workspaces/diff-engine/tests/snapshots/spec_assembler__can_assemble_spec_events_from_serialized_chunks__assembled_events.snap
  workspaces/diff-engine/tests/spec_assembler.rs
Labels: behind-feature-flag, feature
