Repository opticdev/optic, pull requests merged in 2021-03, with the labels that each got.

#615 Fix for optional field interpreters
  workspaces/ui/src/engine/interpreter/interpreter-types/field.ts
Labels: bug

#623 Allow persistence to a single or multiple spec change files through Rust
  .env.beta
  .env.latest
  .env.sidechannel
  workspaces/cli-server/src/routers/spec-router.ts
  workspaces/diff-engine/cli/src/main.rs
  workspaces/diff-engine/lib/index.d.ts
  workspaces/diff-engine/lib/index.js
  workspaces/diff-engine/src/commands/rfc.rs
  workspaces/diff-engine/src/events/rfc.rs
  workspaces/diff-engine/src/events/spec_chunk.rs
  workspaces/diff-engine/src/lib.rs
  workspaces/diff-engine/src/projections/history.rs
  workspaces/diff-engine/src/projections/spec_events.rs
  workspaces/diff-engine/src/streams/spec_chunks.rs
  workspaces/diff-engine/src/streams/spec_events.rs
  workspaces/diff-engine/tests/snapshots/events__spec_should_deserialize.snap
  workspaces/diff-engine/tests/snapshots/spec_assembler__can_assemble_spec_events_from_serialized_chunks__assembled_events.snap
Labels: feature

#627 Write EventContext for each event with new Rust command handler
  Cargo.lock
  workspaces/cli-server/src/routers/spec-router.ts
  workspaces/diff-engine-wasm/engine/Cargo.lock
  workspaces/diff-engine/Cargo.toml
  workspaces/diff-engine/cli/Cargo.toml
  workspaces/diff-engine/cli/src/commit.rs
  workspaces/diff-engine/cli/src/main.rs
  workspaces/diff-engine/lib/index.d.ts
  workspaces/diff-engine/lib/index.js
  workspaces/diff-engine/src/commands/mod.rs
  workspaces/diff-engine/src/commands/rfc.rs
  workspaces/diff-engine/src/commands/snapshots/optic_diff_engine__commands__test__spec_handler_provides_event_context_from_capture_context.snap
  workspaces/diff-engine/src/events/endpoint.rs
  workspaces/diff-engine/src/events/mod.rs
  workspaces/diff-engine/src/events/rfc.rs
  workspaces/diff-engine/src/events/shape.rs
  workspaces/diff-engine/src/lib.rs
Labels: behind-feature-flag

#628 Fix bug where commit messages of batches would contain escape characters
  workspaces/diff-engine/lib/index.js
Labels: behind-feature-flag, fix

#633 Implement processing of spec commands for ExampleSpecService
  workspaces/cli-client/src/spec-service-client.ts
  workspaces/diff-engine-wasm/engine/Cargo.lock
  workspaces/diff-engine-wasm/engine/Cargo.toml
  workspaces/diff-engine-wasm/engine/src/lib.rs
  workspaces/diff-engine/cli/src/commit.rs
  workspaces/diff-engine/src/lib.rs
  workspaces/diff-engine/src/spec/mod.rs
  workspaces/ui/src/components/loaders/ApiLoader.js
Labels: behind-feature-flag

#635 invalid regexes should not crash daemon
  workspaces/cli-config/src/helpers/ignore-parser.ts
Labels: bug

#646 feature: Implement s3 ingest capture saver
  workspaces/analytics/src/events/tasks.ts
  workspaces/cli-shared/package.json
  workspaces/cli-shared/src/captures/avro/file-system/ingest-s3-capture-saver.ts
  workspaces/local-cli/src/commands/ingest/s3.ts
  yarn.lock
Labels: feature
