Repository opticdev/optic, pull requests merged in 2021-06, with the labels that each got.

#845 fixing scroll on win/linux browsers
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/components/BulkLearnModal.tsx
  workspaces/ui-v2/src/pages/diffs/components/DiffCard.tsx
  workspaces/ui-v2/src/pages/docs/components/BodyRender.tsx
Labels: fix

#846 Fix safari path parameter editing
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/components/UndocumentedUrl.tsx
Labels: fix

#852 Blog/its ok to break your api
  website/blog/design-guides-for-api-changes.mdx
  website/blog/its-ok-to-break-your-api.md
  website/blog/live-traffic-beta.md
  website/static/img/blog-content/basic-diff.png
  website/static/img/blog-content/its-ok-to-break-your-api.png
Labels: community

#853 Fix spectacle typings from IBaseSpectacle -> IForkedSpectacle
  workspaces/spectacle-shared/src/local-cli/client.ts
  workspaces/spectacle/src/in-memory/index.ts
  workspaces/ui-v2/src/contexts/spectacle-provider.tsx
  workspaces/ui-v2/src/entry-points/cloud/cloud-viewer.tsx
  workspaces/ui-v2/src/entry-points/demo/demo-examples.tsx
  workspaces/ui-v2/src/entry-points/local/public-examples.tsx
Labels: fix

#850 Handle special characters in api names
  workspaces/ui-v2/src/pages/diffs/components/AuthorIgnoreRule.tsx
  workspaces/ui-v2/src/pages/diffs/contexts/SharedDiffContext.tsx
  workspaces/ui-v2/src/pages/diffs/contexts/SharedDiffState.ts
  workspaces/ui-v2/src/utils/__tests__/pathToRegexpEscaped.test.ts
  workspaces/ui-v2/src/utils/index.ts
  workspaces/ui-v2/src/utils/pathToRegexpEscaped.ts
Labels: fix

#857 Add UI elements for deleting endpoint on documentation page
  .env.latest
  workspaces/ui-v2/src/contexts/config/AppConfiguration.tsx
  workspaces/ui-v2/src/entry-points/cloud/cloud-viewer.tsx
  workspaces/ui-v2/src/entry-points/demo/demo-examples.tsx
  workspaces/ui-v2/src/entry-points/local/local-cli.tsx
  workspaces/ui-v2/src/entry-points/local/public-examples.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/DocumentationRootPage.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/EndpointRow.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/index.ts
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
  workspaces/ui-v2/src/pages/docs/components/DeleteEndpointConfirmationModal.tsx
  workspaces/ui-v2/src/pages/docs/components/EditContributionsButton.tsx
  workspaces/ui-v2/src/pages/docs/components/index.ts
Labels: behind-feature-flag, feature

#861 Fix pending endpoint documentation display
  workspaces/ui-v2/src/pages/diffs/contexts/SimulatedCommandContext.tsx
  workspaces/ui-v2/src/store/root.ts
Labels: fix

#858 Switch out contributions store with redux and connect delete endpoint
  workspaces/spectacle-shared/src/local-cli/client.ts
  workspaces/ui-v2/src/entry-points/local/local-cli.tsx
  workspaces/ui-v2/src/hooks/useClientAgent.ts
  workspaces/ui-v2/src/pages/docs/DocumentationPages.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/DocumentationRootPage.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/EndpointRow.tsx
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
  workspaces/ui-v2/src/pages/docs/components/ContributionGroup.tsx
  workspaces/ui-v2/src/pages/docs/components/Contributions.tsx
  workspaces/ui-v2/src/pages/docs/components/DocPageNavigation.tsx
  workspaces/ui-v2/src/pages/docs/components/EditContributionsButton.tsx
  workspaces/ui-v2/src/pages/docs/components/MarkdownBodyContribution.tsx
  workspaces/ui-v2/src/pages/docs/components/RenderBody.tsx
  workspaces/ui-v2/src/pages/docs/contexts/Contributions.tsx
  workspaces/ui-v2/src/store/documentationEdit.ts
  workspaces/ui-v2/src/store/endpoints.ts
  workspaces/ui-v2/src/store/index.ts
  workspaces/ui-v2/src/store/root.ts
  workspaces/ui-v2/src/store/selectors/documentationEditSelectors.ts
  workspaces/ui-v2/src/store/selectors/index.ts
  workspaces/ui-v2/src/types/contributions.ts
  workspaces/ui-v2/src/types/index.ts
Labels: feature

#863 Disallow editing contributions when endpoint is staged for deletion
  workspaces/ui-v2/src/hooks/useEndpointsChangelog.tsx
  workspaces/ui-v2/src/pages/docs/components/Contributions.tsx
  workspaces/ui-v2/src/pages/docs/components/MarkdownBodyContribution.tsx
Labels: feature

#856 Implement Commands Generator for deleting of Endpoint
  workspaces/optic-engine-wasm/src/lib.rs
  workspaces/optic-engine/src/commands/endpoint.rs
  workspaces/optic-engine/src/commands/snapshots/optic_engine__commands__endpoint__test__can_handle_remove_request_command__new_events.snap
  workspaces/optic-engine/src/commands/snapshots/optic_engine__commands__endpoint__test__can_handle_remove_response_command__new_events.snap
  workspaces/optic-engine/src/events/endpoint.rs
  workspaces/optic-engine/src/interactions/traverser.rs
  workspaces/optic-engine/src/projections/conflicts.rs
  workspaces/optic-engine/src/projections/endpoint.rs
  workspaces/optic-engine/src/projections/history.rs
  workspaces/optic-engine/src/projections/mod.rs
  workspaces/optic-engine/src/queries/endpoint.rs
Labels: feature

#866 Connect endpoint deletion commands to UI via spectacle
  workspaces/spectacle/src/graphql/schema.ts
  workspaces/spectacle/src/index.ts
  workspaces/ui-v2/src/contexts/MetadataLoader.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/EndpointRow.tsx
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
  workspaces/ui-v2/src/pages/docs/components/ContributionGroup.tsx
  workspaces/ui-v2/src/pages/docs/components/Contributions.tsx
  workspaces/ui-v2/src/pages/docs/components/DeleteEndpointConfirmationModal.tsx
  workspaces/ui-v2/src/pages/docs/components/EditContributionsButton.tsx
  workspaces/ui-v2/src/pages/docs/components/MarkdownBodyContribution.tsx
  workspaces/ui-v2/src/pages/docs/components/RenderBody.tsx
  workspaces/ui-v2/src/store/documentationEdit/index.ts
  workspaces/ui-v2/src/store/documentationEdit/slice.ts
  workspaces/ui-v2/src/store/documentationEdit/thunks.ts
  workspaces/ui-v2/src/store/endpoints.ts
  workspaces/ui-v2/src/store/selectors/documentationEditSelectors.ts
Labels: feature

#877 Fix undelete from unstaging all endpoints
  workspaces/ui-v2/src/store/documentationEdit/slice.ts
Labels: fix

#876 Update spectacle projections to handle endpoint deletion
  workspaces/graph-lib/src/endpoints-graph/index.ts
  workspaces/optic-engine/src/projections/spectacle/endpoints.rs
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_1f2c157783b46f9555f537046a7cb37cdde95466bd1af429b0f95f171a2bb4f9__spectacle_endpoints_graph.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_1f2c157783b46f9555f537046a7cb37cdde95466bd1af429b0f95f171a2bb4f9__spectacle_endpoints_json.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_20e9bda8afc0279258c5ac2c01b82c437aa1976e1eba23cb92096f7434d9316c__spectacle_endpoints_graph.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_20e9bda8afc0279258c5ac2c01b82c437aa1976e1eba23cb92096f7434d9316c__spectacle_endpoints_json.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_9949a8cc69a0063a70f5ae98672d8c23a1068a2b2d08f8bb7b9bbd968ec29f0d__spectacle_endpoints_graph.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_9949a8cc69a0063a70f5ae98672d8c23a1068a2b2d08f8bb7b9bbd968ec29f0d__spectacle_endpoints_json.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_af20bd1d8e76cf9db0416175232b9b0276447f7148f3261f2d14b006aa7a0229__spectacle_endpoints_graph.snap
  workspaces/optic-engine/tests/snapshots/domain_conflict_scenarios_generated__scenario_af20bd1d8e76cf9db0416175232b9b0276447f7148f3261f2d14b006aa7a0229__spectacle_endpoints_json.snap
  workspaces/spectacle/src/index.ts
Labels: feature

#878 Handle endpoint removal in changelog
  workspaces/graph-lib/src/endpoints-graph/index.ts
  workspaces/graph-lib/src/index.ts
  workspaces/optic-engine/src/projections/spectacle/endpoints.rs
  workspaces/spectacle/src/graphql/schema.ts
  workspaces/spectacle/src/helpers.ts
  workspaces/spectacle/src/index.ts
  workspaces/ui-v2/src/hooks/useEndpointsChangelog.tsx
  workspaces/ui-v2/src/pages/changelog/ChangelogEndpointRootPage.tsx
  workspaces/ui-v2/src/pages/changelog/ChangelogListPage.tsx
  workspaces/ui-v2/src/pages/changelog/components/ChangelogBackground.tsx
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/AddEndpointsPage.tsx
  workspaces/ui-v2/src/pages/diffs/EndpointDocumentationPane.tsx
  workspaces/ui-v2/src/pages/diffs/ReviewDiffPages.tsx
  workspaces/ui-v2/src/pages/diffs/hooks/useDiffForCapture.ts
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/DocumentationRootPage.tsx
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
  workspaces/ui-v2/src/store/endpoints.ts
  workspaces/ui-v2/src/store/selectors/endpointSelectors.ts
  workspaces/ui-v2/src/store/selectors/index.ts
  workspaces/ui-v2/src/types/endpoints.ts
Labels: feature

#869 Prune unused paths left after deleting endpoints
  workspaces/optic-engine/src/commands/endpoint.rs
  workspaces/optic-engine/src/commands/mod.rs
  workspaces/optic-engine/src/commands/snapshots/optic_engine__commands__endpoint__test__can_handle_remove_path_parameter_command__new_events.snap
  workspaces/optic-engine/src/commands/snapshots/optic_engine__commands__endpoint__test__can_handle_remove_path_parameter_command__path_with_children_result.snap
  workspaces/optic-engine/src/projections/endpoint.rs
  workspaces/optic-engine/src/projections/spectacle/endpoints.rs
  workspaces/optic-engine/src/queries/endpoint.rs
  workspaces/optic-engine/src/queries/mod.rs
  workspaces/optic-engine/src/queries/snapshots/optic_engine__queries__endpoint__test__can_find_unused_paths__unused_paths.snap
  workspaces/optic-engine/src/spec/mod.rs
  workspaces/spectacle/src/commands.ts
  workspaces/spectacle/src/graphql/schema.ts
  workspaces/spectacle/src/index.ts
  workspaces/ui-v2/src/hooks/usePathsHook.ts
  workspaces/ui-v2/src/lib/__tests/__snapshots__/stable-path-batch-generator.test.ts.snap
  workspaces/ui-v2/src/store/documentationEdit/thunks.ts
  workspaces/ui-v2/src/store/endpoints.ts
Labels: feature

#884 fix: Allow minor versions of tokio to be compatible.
  workspaces/optic-engine/Cargo.toml
Labels: fix

#892 Fix endpoint removal when endpoint is the last endpoint in the spec
  workspaces/optic-engine/src/queries/endpoint.rs
  workspaces/ui-v2/src/store/documentationEdit/thunks.ts
Labels: fix

#893 Fix/common start issues
  workspaces/ui-v2/src/pages/changelog/ChangelogListPage.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/DocumentationRootPage.tsx
  workspaces/ui-v2/src/store/endpoints.ts
  workspaces/ui-v2/src/types/endpoints.ts
  workspaces/ui-v2/src/utils/__tests__/findLongestCommonPath.ts
  workspaces/ui-v2/src/utils/__tests__/findLongestStartingSubstring.test.ts
  workspaces/ui-v2/src/utils/findLongestCommonPath.ts
  workspaces/ui-v2/src/utils/findLongestStartingSubstring.ts
  workspaces/ui-v2/src/utils/index.ts
Labels: fix

#903 Prevent root node from being learnt multiple times
  workspaces/optic-engine/src/queries/endpoint.rs
  workspaces/ui-v2/src/hooks/useGroupedEndpoints.ts
  workspaces/ui-v2/src/pages/changelog/ChangelogListPage.tsx
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/AddEndpointsPage.tsx
  workspaces/ui-v2/src/pages/docs/DocumentationRootPage/DocumentationRootPage.tsx
Labels: fix

#898 Ingest capture method
  workspaces/cli-config/src/index.ts
  workspaces/cli-shared/src/ingest/ecs-to-sample.ts
  workspaces/cli-shared/src/ingest/ingest-traffic-service.ts
  workspaces/cli-shared/test/fixtures/ecs-examples/1.json
  workspaces/cli-shared/test/fixtures/ecs-examples/10.json
  workspaces/cli-shared/test/fixtures/ecs-examples/11.json
  workspaces/cli-shared/test/fixtures/ecs-examples/12.json
  workspaces/cli-shared/test/fixtures/ecs-examples/13.json
  workspaces/cli-shared/test/fixtures/ecs-examples/14.json
  workspaces/cli-shared/test/fixtures/ecs-examples/15.json
  workspaces/cli-shared/test/fixtures/ecs-examples/16.json
  workspaces/cli-shared/test/fixtures/ecs-examples/17.json
  workspaces/cli-shared/test/fixtures/ecs-examples/2.json
  workspaces/cli-shared/test/fixtures/ecs-examples/3.json
  workspaces/cli-shared/test/fixtures/ecs-examples/4.json
  workspaces/cli-shared/test/fixtures/ecs-examples/5.json
  workspaces/cli-shared/test/fixtures/ecs-examples/6.json
  workspaces/cli-shared/test/fixtures/ecs-examples/7.json
  workspaces/cli-shared/test/fixtures/ecs-examples/8.json
  workspaces/cli-shared/test/fixtures/ecs-examples/9.json
  workspaces/cli-shared/test/tap-snapshots/tests-ecs.ts-TAP.test.js
  workspaces/cli-shared/test/tests/ecs.ts
  workspaces/local-cli/src/commands/exec.ts
  workspaces/local-cli/src/commands/run.ts
  workspaces/local-cli/src/shared/ingest-only-task-runner.ts
  workspaces/local-cli/src/shared/local-cli-task-runner.ts
Labels: feature

#905 fix ecs test-case
  workspaces/cli-shared/test/tap-snapshots/tests-ecs.ts-TAP.test.js
  workspaces/cli-shared/test/tests/ecs.ts
Labels: fix

#904 Fix capture for context type text/html with no text body
  workspaces/cli-shared/src/httptoolkit-capturing-proxy.ts
  workspaces/ui-v2/src/pages/diffs/ReviewEndpointDiffPage/ReviewEndpointDiffPageContainer.tsx
Labels: fix

#906 Fix rust snapshot tests
  workspaces/optic-engine/tests/snapshots/events__spec_should_deserialize.snap
Labels: fix

#908 fixed isCommandOnly logic
  workspaces/cli-config/src/index.ts
Labels: fix

#909 Fix intercept mode not being able to diff
  workspaces/cli-server/src/server.ts
  workspaces/local-cli/src/commands/intercept.ts
Labels: fix

#897 Feature: Spec sharing
  .github/workflows/build-ui-v2.yml
  workspaces/analytics/src/uiEvents.ts
  workspaces/ui-v2/package.json
  workspaces/ui-v2/src/components/DebugOpticComponent.tsx
  workspaces/ui-v2/src/components/navigation/TopNavigation.tsx
  workspaces/ui-v2/src/components/sharing/ShareButton.tsx
  workspaces/ui-v2/src/components/sharing/ShareModal.tsx
  workspaces/ui-v2/src/constants/LogoSvg.ts
  workspaces/ui-v2/src/contexts/SpecRepositoryContext.tsx
  workspaces/ui-v2/src/contexts/config/AppConfiguration.tsx
  workspaces/ui-v2/src/entry-points/cloud/cloud-viewer.tsx
  workspaces/ui-v2/src/entry-points/demo/demo-examples.tsx
  workspaces/ui-v2/src/entry-points/local/local-cli.tsx
  workspaces/ui-v2/src/entry-points/local/public-examples.tsx
  workspaces/ui-v2/src/utils/encodeQueryParams.ts
  yarn.lock
Labels: feature

#918 Implement a basic History page UI
  workspaces/ui-v2/src/components/navigation/NavButton.tsx
  workspaces/ui-v2/src/components/navigation/Routes.ts
  workspaces/ui-v2/src/components/navigation/TopNavigation.tsx
  workspaces/ui-v2/src/entry-points/cloud/cloud-viewer.tsx
  workspaces/ui-v2/src/entry-points/demo/demo-examples.tsx
  workspaces/ui-v2/src/entry-points/local/local-cli.tsx
  workspaces/ui-v2/src/entry-points/local/public-examples.tsx
  workspaces/ui-v2/src/pages/changelogHistory/ChangelogHistory.tsx
Labels: feature

#920 Fix UI gql queries
  workspaces/spectacle-shared/src/local-cli/client.ts
  workspaces/ui-v2/src/store/documentationEdit/thunks.ts
Labels: fix

#922 Fix double enter press when confirming change
  workspaces/ui-v2/src/components/CommitMessageModal.tsx
Labels: fix

#914 Implement reset to commit spectacle commands
  .gitignore
  workspaces/cli-config/src/index.ts
  workspaces/cli-server/src/spectacle/index.ts
  workspaces/optic-domain/src/async-tools.ts
  workspaces/optic-domain/src/streams/index.ts
  workspaces/optic-domain/src/streams/spec-events.ts
  workspaces/optic-domain/tap-snapshots/tests-streams-spec-events.ts-TAP.test.js
  workspaces/optic-domain/tests/streams/spec-events.ts
  workspaces/spectacle-shared/src/local-cli/client.ts
  workspaces/spectacle/src/graphql/schema.ts
  workspaces/spectacle/src/in-memory/index.ts
  workspaces/spectacle/src/spectacle.ts
  workspaces/spectacle/src/types.ts
  workspaces/ui-v2/src/entry-points/local/local-cli.tsx
Labels: feature

#919 Add in confirm reset modal and hook up UI to spectacle
  workspaces/analytics/src/uiEvents.ts
  workspaces/ui-v2/package.json
  workspaces/ui-v2/src/components/Button.tsx
  workspaces/ui-v2/src/components/CommitMessageModal.tsx
  workspaces/ui-v2/src/components/index.ts
  workspaces/ui-v2/src/components/navigation/NavButton.tsx
  workspaces/ui-v2/src/pages/changelogHistory/ChangelogHistory.tsx
  workspaces/ui-v2/src/pages/changelogHistory/components/ConfirmResetModal.tsx
  workspaces/ui-v2/src/pages/changelogHistory/components/index.ts
  workspaces/ui-v2/src/styles/theme.ts
  yarn.lock
Labels: feature

#925 Fix lint error
  workspaces/ui-v2/src/pages/changelogHistory/ChangelogHistory.tsx
Labels: fix

#928 feature: Show request method in coverage report
  workspaces/local-cli/src/shared/coverage.ts
Labels: feature

#942 Change path parameter matcher to use a fn instead of pathToRegexp lib
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/AddEndpointsPage.tsx
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/components/BulkLearnModal.tsx
  workspaces/ui-v2/src/pages/diffs/AddEndpointsPage/components/UndocumentedUrl.tsx
  workspaces/ui-v2/src/pages/diffs/contexts/SharedDiffContext.tsx
  workspaces/ui-v2/src/pages/diffs/contexts/SharedDiffState.ts
  workspaces/ui-v2/src/utils/__tests__/findLongestCommonPath.test.ts
  workspaces/ui-v2/src/utils/__tests__/pathMatcher.test.ts
  workspaces/ui-v2/src/utils/__tests__/pathToRegexpEscaped.test.ts
  workspaces/ui-v2/src/utils/index.ts
  workspaces/ui-v2/src/utils/pathMatcher.ts
  workspaces/ui-v2/src/utils/pathToRegexpEscaped.ts
Labels: fix

#944 Fix react fragment warning
  workspaces/ui-v2/src/pages/changelog/components/ChangelogDropdown.tsx
Labels: fix

#936 Feature/query param UI mock
  workspaces/spectacle/src/graphql/schema.ts
  workspaces/spectacle/src/helpers.ts
  workspaces/spectacle/src/spectacle.ts
Labels: feature
