Repository opticdev/optic, pull requests merged in 2021-08, with the labels that each got.

#1073 Fix polymorphic shape viewing
  workspaces/ui-v2/src/store/shapes/thunks.ts
Labels: fix

#1081 Fix so that optional now shows up in contributions list
  workspaces/ui-v2/src/components/FieldOrParameter.tsx
  workspaces/ui-v2/src/components/PathParameters.tsx
  workspaces/ui-v2/src/components/ShapeRenderer/ShapeRowBase.tsx
  workspaces/ui-v2/src/pages/changelog/ChangelogEndpointRootPage.tsx
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
  workspaces/ui-v2/src/pages/docs/components/Contributions.tsx
  workspaces/ui-v2/src/store/selectors/__tests__/__snapshots__/shapeSelectors.test.ts.snap
  workspaces/ui-v2/src/store/selectors/shapeSelectors.ts
  workspaces/ui-v2/src/types/shapes.ts
Labels: fix

#1082 Raise errors when calling listDiffs and listUnrecognizedUrls
  workspaces/spectacle-shared/src/local-cli/client.ts
Labels: fix

#1091 add browser only to main page
  website/src/pages/index.js
Labels: fix

#1084 Handle array object fields being deleted
  workspaces/ui-v2/src/store/selectors/__tests__/documentationEditSelectors.test.ts
  workspaces/ui-v2/src/store/selectors/__tests__/testHelpers.ts
  workspaces/ui-v2/src/store/selectors/documentationEditSelectors.ts
Labels: fix

#1089 Fix cloud viewer from being able to reach edit mode
  workspaces/ui-v2/src/pages/docs/components/Contributions.tsx
Labels: fix

#1090 Query param not showing up in endpoint changes
  workspaces/graph-lib/src/endpoints-graph/index.ts
  workspaces/spectacle/src/helpers.ts
  workspaces/ui-v2/src/pages/changelog/components/ChangelogBackground.tsx
Labels: fix

#1092 fix ui-v2 yarn ws:build
  workspaces/ui-v2/src/store/selectors/documentationEditSelectors.ts
Labels: fix

#1093 fix: Plumb the spec ID through correctly
  workspaces/cli-client/src/client.ts
  workspaces/local-cli/src/shared/analytics.ts
  workspaces/ui-v2/src/components/sharing/ShareButton.tsx
Labels: fix

#1085 Improve how Typescript compiles across the monorepo
  .gitignore
  Taskfile.yml
  tsconfig.base.json
  tsconfig.json
  workspaces/analytics/package.json
  workspaces/analytics/tsconfig.json
  workspaces/api-checks/package.json
  workspaces/api-checks/tsconfig.json
  workspaces/changelog/package.json
  workspaces/changelog/tsconfig.json
  workspaces/cli-client/package.json
  workspaces/cli-client/tsconfig.json
  workspaces/cli-config/package.json
  workspaces/cli-config/tsconfig.json
  workspaces/cli-scripts/package.json
  workspaces/cli-scripts/tsconfig.json
  workspaces/cli-server/package.json
  workspaces/cli-server/src/index.ts
  workspaces/cli-server/tsconfig.json
  workspaces/cli-shared/package.json
  workspaces/cli-shared/src/captures/avro/file-system/capture-saver.ts
  workspaces/cli-shared/src/captures/avro/file-system/dump-capture-saver.ts
  workspaces/cli-shared/src/captures/avro/file-system/replicated-interactions-capture-saver.ts
  workspaces/cli-shared/src/captures/avro/file-system/snapshot-input-capture-saver.ts
  workspaces/cli-shared/src/captures/avro/saas/capture-saver.ts
  workspaces/cli-shared/src/command-and-proxy-session-manager.ts
  workspaces/cli-shared/src/command-session.ts
  workspaces/cli-shared/tsconfig.json
  workspaces/client-utilities/package.json
  workspaces/client-utilities/tsconfig.json
  workspaces/graph-lib/package.json
  workspaces/graph-lib/tsconfig.json
  workspaces/local-cli/package.json
  workspaces/local-cli/tsconfig.json
  workspaces/optic-domain/package.json
  workspaces/optic-domain/tsconfig.json
  workspaces/optic-engine-wasm/package.json
  workspaces/optic-engine-wasm/scripts/watch.js
  workspaces/optic-engine-wasm/webpack.plugin.js
  workspaces/saas-types/package.json
  workspaces/saas-types/tsconfig.json
  workspaces/shape-hash/package.json
  workspaces/shape-hash/tsconfig.json
  workspaces/snapshot-tests/package.json
  workspaces/snapshot-tests/tsconfig.json
  workspaces/spectacle-shared/package.json
  workspaces/spectacle-shared/tsconfig.json
  workspaces/spectacle/package.json
  workspaces/spectacle/tsconfig.json
  workspaces/ui-v2/tsconfig.json
Labels: chore

#1094 Fix Typescript compilation for ui-v2
  workspaces/ui-v2/package.json
  workspaces/ui-v2/tsconfig.json
Labels: chore

#1097 Fix/diff navigation prompting
  workspaces/ui-v2/src/components/PromptNavigateAway.tsx
  workspaces/ui-v2/src/pages/diffs/components/DiffAccessoryNavigation.tsx
Labels: fix

#1101 Implement new Shape Editor UI
  workspaces/ui-v2/package.json
  workspaces/ui-v2/src/components/HttpBodyPanel.tsx
  workspaces/ui-v2/src/components/ShapeRenderer/ShapePrimitive.tsx
  workspaces/ui-v2/src/components/ShapeRenderer/ShapeRowBase.tsx
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
  workspaces/ui-v2/src/pages/docs/components/ShapeEditor.tsx
  workspaces/ui-v2/src/pages/docs/components/index.ts
  workspaces/ui-v2/src/styles/theme.ts
  workspaces/ui-v2/tsconfig.json
Labels: behind-feature-flag, feature

#1108 Fix daemon version mismatch
  workspaces/ui-v2/src/entry-points/local/EnsureDaemonRunning.tsx
Labels: fix

#1105 Only render the ShapeEditor and selected field highlights in edit mode
  workspaces/ui-v2/src/pages/docs/EndpointRootPage.tsx
Labels: behind-feature-flag

#1125 Fix bug where fields with unknown shapes can't be edited
  workspaces/optic-engine/src/queries/shape.rs
  workspaces/optic-engine/src/queries/snapshots/optic_engine__queries__shape__test__can_generate_edit_shape_trail_commands_to_make_unknown_nullable_field_optional__choice_mapping.snap
  workspaces/optic-engine/src/queries/snapshots/optic_engine__queries__shape__test__can_generate_edit_shape_trail_commands_to_make_unknown_nullable_field_optional__commands.snap
  workspaces/optic-engine/src/queries/snapshots/optic_engine__queries__shape__test__can_resolve_shape_trails__unknown_nullable_trail.snap
  workspaces/optic-engine/src/queries/spectacle/spec_choices.rs
  workspaces/optic-engine/src/shapes/traverser.rs
Labels: fix
